src/Entity/Decision.php
<?php

namespace App\Entity;

use App\Repository\DecisionRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints\DateTime;

/**
 * @ORM\Entity(repositoryClass=DecisionRepository::class)
 */
class Decision
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity=Speaker::class, inversedBy="decisions")
     */
    private $speaker;

    /**
     * @ORM\ManyToOne(targetEntity=Decidable::class, inversedBy="decisions")
     */
    private $decidable;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    public function __construct()
    {
        $this->setCreatedAt(new \DateTime('now'));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getSpeaker(): ?Speaker
    {
        return $this->speaker;
    }

    public function setSpeaker(?Speaker $speaker): self
    {
        $this->speaker = $speaker;

        return $this;
    }

    public function getDecidable(): ?Decidable
    {
        return $this->decidable;
    }

    public function setDecidable(?Decidable $decidable): self
    {
        $this->decidable = $decidable;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Controller/FrontController.php
<?php

namespace App\Controller;

use App\Repository\DecidableRepository;
use App\Repository\DecisionRepository;
use App\Repository\SpeakerRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
* @Route("", name="front_")
*/

class FrontController extends AbstractController
{
    /**
     * @Route("/", name="index")
     * @param SpeakerRepository $speakerRepository
     * @param DecidableRepository $decidableRepository
     * @param DecisionRepository $decisionRepository
     * @return Response
     */
    public function index(SpeakerRepository $speakerRepository,
                          DecidableRepository $decidableRepository,
                          DecisionRepository $decisionRepository): Response
    {
        $speakers =  $speakerRepository->findAll();
        $decidables = $decidableRepository->findAll();
        $decisions = $decisionRepository->findAll();

        return $this->render('front/index.html.twig',
            compact(['speakers', 'decidables', 'decisions'])
        );
    }
}

templates/front/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello FrontController!{% endblock %}

{% block body %}
<div class="example-wrapper">
    <h1>Cellule de décision COVID</h1>

    <h2>Liste des décisions</h2>
    <ul>
        {%  for decision in decisions %}
            <h3>{{ decision.decidable.label }}</h3>
            <h4>{{ decision.speaker }} {{ decision.createdAt|date("d/m/Y h:i:s") }}</h4>
            <p>{{ decision.decidable.desciption }}</p>
            <hr>
        {% endfor %}
    </ul>

    <hr/>

    <h3>Liste des speakers</h3>
    <ul>
        {%  for speaker in speakers %}
            <li>{{ speaker.firstname }} {{ speaker.lastname }}</li>
        {% endfor %}
    </ul>

    <hr/>
    
    <h3>Liste des hypotheses</h3>
    <ul>
        {%  for decidable in decidables %}
            <li>{{ decidable.label }}</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}